export const BODY_SYSTEMS: string[] = [
  "Cuore / Sistema cardiovascolare",
  "Polmoni / Sistema respiratorio",
  "Cervello / Sistema neurologico",
  "Stomaco / Apparato digerente",
  "Intestino",
  "Fegato",
  "Reni / Apparato urinario",
  "Tiroide / Sistema endocrino",
  "Ginocchio",
  "Spalla",
  "Schiena / Colonna vertebrale",
  "Pelle",
  "Occhi",
  "Orecchie",
  "Apparato ginecologico",
  "Apparato urologico",
  "Sangue / Sistema ematologico",
  "Sistema immunitario",
  "Salute generale",
];
